name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3.0"
          - "3.2.3"
          - "3.1.4"
          - "3.0.3"
          - "truffleruby-23.1.2"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the tests
        run: bin/rake test
      - name: Run the conformance tests
        uses: sigstore/sigstore-conformance@v0.0.11
        with:
          entrypoint: ${{ github.workspace }}/bin/conformance-entrypoint
          xfail: test_verify_trust_root_with_invalid_ct_keys test_verify_dsse_bundle_with_trust_root
          skip-signing: true
      - name: Run the conformance tests against staging
        uses: sigstore/sigstore-conformance@v0.0.11
        with:
          entrypoint: ${{ github.workspace }}/bin/conformance-entrypoint
          xfail: test_verify_trust_root_with_invalid_ct_keys test_verify_dsse_bundle_with_trust_root
          environment: staging
          skip-signing: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        if: ${{ matrix.ruby }} == "3.3.0" && always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: segiddins/sigstore-cosign-verify

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true
      - name: Run the linter
        run: bin/rubocop
